# Generated by Django 6.0.6 on 2026-06-20 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('motion', 'حركة'), ('person', 'شخص'), ('object', 'جسم')], max_length=20)),
                ('message', models.TextField()),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='alerts/')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.IntegerField()),
                ('bbox_y1', models.IntegerField()),
                ('bbox_x2', models.IntegerField()),
                ('bbox_y2', models.IntegerField()),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
