# Generated by Django 6.0.6 on 2026-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_alert_is_read_alter_detection_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='person_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('motion', 'حركة'), ('person', 'شخص'), ('person_stranger', 'شخص غريب'), ('person_known', 'شخص معروف')], max_length=20),
        ),
    ]
